// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Text.DI.TextHelperServiceTests.RemoveDiacritics_ShouldRemoveCorrectly(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Text.DI.TextHelperServiceTests.CapitalizeFirst_ShouldCapitalizeFirstLetter(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Text.DI.TextHelperServiceTests.ConvertNewLines_ShouldConvertCorrectly(System.String,Afrowave.SharedTools.Models.Enums.TextNewLineStyle,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Text.DI.TextHelperServiceTests.Truncate_ShouldRespectMaxLength(System.String,System.Int32,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Text.DI.TextHelperServiceTests.Slugify_ShouldGenerateUrlSafeSlug(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Afrowave.SharedTools.Text.DI.TextHelperServiceTests.RemoveDiacritics_ShouldRemoveCorrectly(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Afrowave.SharedTools.Text.DI.TextHelperServiceTests.CapitalizeFirst_ShouldCapitalizeFirstLetter(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Afrowave.SharedTools.Text.DI.TextHelperServiceTests.ConvertNewLines_ShouldConvertCorrectly(System.String,Afrowave.SharedTools.Models.Enums.TextNewLineStyle,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Afrowave.SharedTools.Text.DI.TextHelperServiceTests.Truncate_ShouldRespectMaxLength(System.String,System.Int32,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Afrowave.SharedTools.Text.DI.TextHelperServiceTests.Slugify_ShouldGenerateUrlSafeSlug(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1012:Null should only be used for nullable parameters", Justification = "<Čeká>", Scope = "member", Target = "~M:Afrowave.SharedTools.Tests.Afrowave.SharedTools.Text.DI.TextHelperServiceTests.Unslugify_ShouldReplaceDashesWithSpaces(System.String,System.String)")]